<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Squirix.E2ETests</RootNamespace>
        <AssemblyName>Squirix.E2ETests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.IdentityModel.Tokens"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\squirix\Squirix.csproj"/>
        <ProjectReference Include="..\squirix.server\squirix.server.testkit\Squirix.Server.TestKit.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="..\xunit.runner.json" Link="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>
