<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Squirix.Server.SmokeTests</RootNamespace>
        <AssemblyName>Squirix.Server.SmokeTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\squirix.server.testkit\Squirix.Server.TestKit.csproj"/>
        <ProjectReference Include="..\..\..\src\squirix.server\Squirix.Server.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\xunit.runner.json" Link="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>