<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Squirix.IntegrationTests</RootNamespace>
        <AssemblyName>Squirix.IntegrationTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\squirix.testkit\Squirix.TestKit.csproj"/>
        <ProjectReference Include="..\..\..\src\squirix\Squirix.csproj"/>
    </ItemGroup>
</Project>