using Microsoft.Extensions.Logging;

namespace Squirix.Server.Logging;

/// <summary>
/// Centralized, strongly-typed logging templates for Squirix.
/// Declared as <c>partial</c>; bodies are generated by the <see cref="LoggerMessageAttribute" /> source generator.
/// </summary>
internal static partial class LogManager
{
    static LogManager()
    {
        _ = LogFilter.ShouldLog(LogLevel.Information);
        _ = LogFormatter.Format("init");
        _ = LogRouting.Route("server");
    }
}
