services:
  node-a:
    build:
      context: ..
      dockerfile: Dockerfile.release
      args:
        SQUIRIX_VERSION: 0.1.0-preview.4
        LOCAL_PACKAGES: "true"
    container_name: squirix-node-a-release
    environment:
      - SQUIRIX_JWT_SIGNING_KEY=dev-squirix-docker-jwt-key!!!!!!
      - SQUIRIX_JWT_ISSUER=https://squirix.docker.dev
      - SQUIRIX_JWT_AUDIENCE=squirix
    command: ["run", "--persist", "--data-dir", "/data"]
    ports:
      - "5001:5000"
    volumes:
      - ./node-a/Squirix.settings.json:/app/Squirix.settings.json:ro
      - nodea-data:/data
    networks:
      - squirix-net

  node-b:
    build:
      context: ..
      dockerfile: Dockerfile.release
      args:
        SQUIRIX_VERSION: 0.1.0-preview.4
        LOCAL_PACKAGES: "true"
    container_name: squirix-node-b-release
    environment:
      - SQUIRIX_JWT_SIGNING_KEY=dev-squirix-docker-jwt-key!!!!!!
      - SQUIRIX_JWT_ISSUER=https://squirix.docker.dev
      - SQUIRIX_JWT_AUDIENCE=squirix
    command: ["run", "--persist", "--data-dir", "/data"]
    ports:
      - "5002:5000"
    volumes:
      - ./node-b/Squirix.settings.json:/app/Squirix.settings.json:ro
      - nodeb-data:/data
    networks:
      - squirix-net

volumes:
  nodea-data: {}
  nodeb-data: {}

networks:
  squirix-net:
    driver: bridge
