<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Squirix.TestKit</RootNamespace>
        <AssemblyName>Squirix.TestKit</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <PackageReference Include="xunit.v3.assert"/>
        <PackageReference Include="xunit.v3.extensibility.core"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\..\src\squirix.attributes\SquirixAttribute.cs" Link="Attributes\SquirixAttribute.cs"/>
        <Compile Include="..\..\..\src\squirix.attributes\ImmutableAttribute.cs" Link="Attributes\ImmutableAttribute.cs"/>
    </ItemGroup>
</Project>