<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Squirix.TestKit</RootNamespace>
        <AssemblyName>Squirix.TestKit</AssemblyName>
    </PropertyGroup>
</Project>
