<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <RootNamespace>Squirix.ProtocolModel</RootNamespace>
        <AssemblyName>Squirix.ProtocolModel</AssemblyName>
        <StartupObject>Squirix.ProtocolModel.Program</StartupObject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Squirix.ProtocolModel.Tests"/>
        <InternalsVisibleTo Include="Squirix.Server.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\squirix.attributes\SquirixAttribute.cs" Link="Attributes\SquirixAttribute.cs"/>
        <Compile Include="..\squirix.attributes\ImmutableAttribute.cs" Link="Attributes\ImmutableAttribute.cs"/>
    </ItemGroup>
</Project>
