<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <RootNamespace>Squirix.ProtocolModel.Tests</RootNamespace>
        <AssemblyName>Squirix.ProtocolModel.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\squirix.protocol-model\Squirix.ProtocolModel.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="..\..\xunit.runner.json" Link="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>
