<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Squirix.Server.IntegrationTests</RootNamespace>
        <AssemblyName>Squirix.Server.IntegrationTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client"/>
        <PackageReference Include="Google.Protobuf"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
        <PackageReference Include="Microsoft.IdentityModel.Tokens"/>
        <PackageReference Include="JetBrains.Annotations"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\squirix.server.testkit\Squirix.Server.TestKit.csproj"/>
        <ProjectReference Include="..\..\..\src\squirix.server\Squirix.Server.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="..\..\xunit.runner.json" Link="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>
